### ISSUE TITLE
complie Linux kernel with LLVM

### ISSUE THREAD

**Issue by DemoAuguste** [kengiter/lrsan#1]
Hi,
I encountered some problems when compiling the Linux kernel with LLVM. Could you describe the detailed steps of compiling the  Linux kernel?

Thanks

**Comment by kengiter** [comment]
I've just updated the README.

We have our own tool to generate bitcode files: https://github.com/sslab-gatech/deadline/tree/release/work. Note that files (typically less than 10) with compilation errors are simply discarded.
Alternatively, you can use LLVMLinux and clang-kernel-build (https://github.com/ramosian-glider/clang-kernel-build).
