### ISSUE TITLE
Having no result running Lrsan

### ISSUE THREAD

**Issue by G0o9leA1** [kengiter/lrsan#2]
Hi, I am trying to reproduce your work in the paper and encounter some issues.

Operating system: Ubuntu 16.04
LLVM version: 7.0.0
 
I successfully build llvm and lrsan analyzer. For preparing llvm bitcode files I am using your tool to successfully generate 16802 bitcode files(for linux kernel 4.17).

However, after I run the lrsan, it shows nothing about the lacking recheck bugs. The output I am getting is like:

[CallGraph] Initializing 16802 modules.....
[CallGraph /1][1/16082][$bcfile's path]
...
[CallGraph /1][16082/16082][$bcfile's path]
[CallGraph] Updated in 0 modules.
[CallGraph] Postprocessing ...
[CallGraph] Done!

[PointerAnalysis] Initializing 16802 modules.....
[PointerAnalysis /1][1/16082][$bcfile's path]
...
[PointerAnalysis /1][16082/16082][$bcfile's path]
[PointerAnalysis] Updated in 0 modules.
[PointerAnalysis] Postprocessing ...
[PointerAnalysis] Done!

[CriticalVar] Initializing 16802 modules.....
[CriticalVar /1][1/16082][$bcfile's path]
...
[CriticalVar /1][16082/16082][$bcfile's path]
[CriticalVar] Updated in 0 modules.
[CriticalVar] Postprocessing ...
[CriticalVar] Done!

**Comment by kengiter** [comment]
This is probably because error codes are not redefine with magic code. You will need to peplace error-code definition files of the Linux kernel with the ones in the folder "encoded-errno".

**Comment by G0o9leA1** [comment]
Oh, I see. I was doing the reverse. I replaced files in folder 'encoded-errno' with the linux kernel ones.

Thanks for you help! :)

**Comment by yyxRoy** [comment]
Hi @G0o9leA1, I am reproducing this work now and I have met the same question as you stated above. After I replaced the error-code definition files as @kengiter said, the output is still the same as before. I'd like to know where and how to get the analysis result or the output. Please.
